/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XRouteImport } from './routes/x'
import { Route as LinkedinRouteImport } from './routes/linkedin'
import { Route as JoinWaitlistRouteImport } from './routes/join-waitlist'
import { Route as GithubRouteImport } from './routes/github'
import { Route as FoundersRouteImport } from './routes/founders'
import { Route as DiscordRouteImport } from './routes/discord'
import { Route as CalRouteImport } from './routes/cal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ViewRouteRouteImport } from './routes/_view/route'
import { Route as ViewIndexRouteImport } from './routes/_view/index'
import { Route as WebhookStripeRouteImport } from './routes/webhook/stripe'
import { Route as WebhookNangoRouteImport } from './routes/webhook/nango'
import { Route as ViewPricingRouteImport } from './routes/_view/pricing'
import { Route as ViewDocsRouteRouteImport } from './routes/_view/docs/route'
import { Route as ViewAppRouteRouteImport } from './routes/_view/app/route'
import { Route as ViewProductIndexRouteImport } from './routes/_view/product/index'
import { Route as ViewLegalIndexRouteImport } from './routes/_view/legal/index'
import { Route as ViewDownloadIndexRouteImport } from './routes/_view/download/index'
import { Route as ViewDocsIndexRouteImport } from './routes/_view/docs/index'
import { Route as ViewChangelogIndexRouteImport } from './routes/_view/changelog/index'
import { Route as ViewBlogIndexRouteImport } from './routes/_view/blog/index'
import { Route as ViewAppIndexRouteImport } from './routes/_view/app/index'
import { Route as ViewLegalSlugRouteImport } from './routes/_view/legal/$slug'
import { Route as ViewDownloadAppleSiliconRouteImport } from './routes/_view/download/apple-silicon'
import { Route as ViewDocsSlugRouteImport } from './routes/_view/docs/$slug'
import { Route as ViewChangelogSlugRouteImport } from './routes/_view/changelog/$slug'
import { Route as ViewCallbackAuthRouteImport } from './routes/_view/callback/auth'
import { Route as ViewBlogSlugRouteImport } from './routes/_view/blog/$slug'
import { Route as ViewAppIntegrationRouteImport } from './routes/_view/app/integration'
import { Route as ViewAppAccountRouteImport } from './routes/_view/app/account'

const XRoute = XRouteImport.update({
  id: '/x',
  path: '/x',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinRoute = LinkedinRouteImport.update({
  id: '/linkedin',
  path: '/linkedin',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinWaitlistRoute = JoinWaitlistRouteImport.update({
  id: '/join-waitlist',
  path: '/join-waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersRoute = FoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscordRoute = DiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const CalRoute = CalRouteImport.update({
  id: '/cal',
  path: '/cal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewRouteRoute = ViewRouteRouteImport.update({
  id: '/_view',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewIndexRoute = ViewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ViewRouteRoute,
} as any)
const WebhookStripeRoute = WebhookStripeRouteImport.update({
  id: '/webhook/stripe',
  path: '/webhook/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhookNangoRoute = WebhookNangoRouteImport.update({
  id: '/webhook/nango',
  path: '/webhook/nango',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewPricingRoute = ViewPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewDocsRouteRoute = ViewDocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewAppRouteRoute = ViewAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewProductIndexRoute = ViewProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewLegalIndexRoute = ViewLegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewDownloadIndexRoute = ViewDownloadIndexRouteImport.update({
  id: '/download/',
  path: '/download/',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewDocsIndexRoute = ViewDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ViewDocsRouteRoute,
} as any)
const ViewChangelogIndexRoute = ViewChangelogIndexRouteImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewBlogIndexRoute = ViewBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewAppIndexRoute = ViewAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ViewAppRouteRoute,
} as any)
const ViewLegalSlugRoute = ViewLegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewDownloadAppleSiliconRoute =
  ViewDownloadAppleSiliconRouteImport.update({
    id: '/download/apple-silicon',
    path: '/download/apple-silicon',
    getParentRoute: () => ViewRouteRoute,
  } as any)
const ViewDocsSlugRoute = ViewDocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ViewDocsRouteRoute,
} as any)
const ViewChangelogSlugRoute = ViewChangelogSlugRouteImport.update({
  id: '/changelog/$slug',
  path: '/changelog/$slug',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewCallbackAuthRoute = ViewCallbackAuthRouteImport.update({
  id: '/callback/auth',
  path: '/callback/auth',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewBlogSlugRoute = ViewBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => ViewRouteRoute,
} as any)
const ViewAppIntegrationRoute = ViewAppIntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => ViewAppRouteRoute,
} as any)
const ViewAppAccountRoute = ViewAppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ViewAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/cal': typeof CalRoute
  '/discord': typeof DiscordRoute
  '/founders': typeof FoundersRoute
  '/github': typeof GithubRoute
  '/join-waitlist': typeof JoinWaitlistRoute
  '/linkedin': typeof LinkedinRoute
  '/x': typeof XRoute
  '/app': typeof ViewAppRouteRouteWithChildren
  '/docs': typeof ViewDocsRouteRouteWithChildren
  '/pricing': typeof ViewPricingRoute
  '/webhook/nango': typeof WebhookNangoRoute
  '/webhook/stripe': typeof WebhookStripeRoute
  '/': typeof ViewIndexRoute
  '/app/account': typeof ViewAppAccountRoute
  '/app/integration': typeof ViewAppIntegrationRoute
  '/blog/$slug': typeof ViewBlogSlugRoute
  '/callback/auth': typeof ViewCallbackAuthRoute
  '/changelog/$slug': typeof ViewChangelogSlugRoute
  '/docs/$slug': typeof ViewDocsSlugRoute
  '/download/apple-silicon': typeof ViewDownloadAppleSiliconRoute
  '/legal/$slug': typeof ViewLegalSlugRoute
  '/app/': typeof ViewAppIndexRoute
  '/blog': typeof ViewBlogIndexRoute
  '/changelog': typeof ViewChangelogIndexRoute
  '/docs/': typeof ViewDocsIndexRoute
  '/download': typeof ViewDownloadIndexRoute
  '/legal': typeof ViewLegalIndexRoute
  '/product': typeof ViewProductIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/cal': typeof CalRoute
  '/discord': typeof DiscordRoute
  '/founders': typeof FoundersRoute
  '/github': typeof GithubRoute
  '/join-waitlist': typeof JoinWaitlistRoute
  '/linkedin': typeof LinkedinRoute
  '/x': typeof XRoute
  '/pricing': typeof ViewPricingRoute
  '/webhook/nango': typeof WebhookNangoRoute
  '/webhook/stripe': typeof WebhookStripeRoute
  '/': typeof ViewIndexRoute
  '/app/account': typeof ViewAppAccountRoute
  '/app/integration': typeof ViewAppIntegrationRoute
  '/blog/$slug': typeof ViewBlogSlugRoute
  '/callback/auth': typeof ViewCallbackAuthRoute
  '/changelog/$slug': typeof ViewChangelogSlugRoute
  '/docs/$slug': typeof ViewDocsSlugRoute
  '/download/apple-silicon': typeof ViewDownloadAppleSiliconRoute
  '/legal/$slug': typeof ViewLegalSlugRoute
  '/app': typeof ViewAppIndexRoute
  '/blog': typeof ViewBlogIndexRoute
  '/changelog': typeof ViewChangelogIndexRoute
  '/docs': typeof ViewDocsIndexRoute
  '/download': typeof ViewDownloadIndexRoute
  '/legal': typeof ViewLegalIndexRoute
  '/product': typeof ViewProductIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_view': typeof ViewRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cal': typeof CalRoute
  '/discord': typeof DiscordRoute
  '/founders': typeof FoundersRoute
  '/github': typeof GithubRoute
  '/join-waitlist': typeof JoinWaitlistRoute
  '/linkedin': typeof LinkedinRoute
  '/x': typeof XRoute
  '/_view/app': typeof ViewAppRouteRouteWithChildren
  '/_view/docs': typeof ViewDocsRouteRouteWithChildren
  '/_view/pricing': typeof ViewPricingRoute
  '/webhook/nango': typeof WebhookNangoRoute
  '/webhook/stripe': typeof WebhookStripeRoute
  '/_view/': typeof ViewIndexRoute
  '/_view/app/account': typeof ViewAppAccountRoute
  '/_view/app/integration': typeof ViewAppIntegrationRoute
  '/_view/blog/$slug': typeof ViewBlogSlugRoute
  '/_view/callback/auth': typeof ViewCallbackAuthRoute
  '/_view/changelog/$slug': typeof ViewChangelogSlugRoute
  '/_view/docs/$slug': typeof ViewDocsSlugRoute
  '/_view/download/apple-silicon': typeof ViewDownloadAppleSiliconRoute
  '/_view/legal/$slug': typeof ViewLegalSlugRoute
  '/_view/app/': typeof ViewAppIndexRoute
  '/_view/blog/': typeof ViewBlogIndexRoute
  '/_view/changelog/': typeof ViewChangelogIndexRoute
  '/_view/docs/': typeof ViewDocsIndexRoute
  '/_view/download/': typeof ViewDownloadIndexRoute
  '/_view/legal/': typeof ViewLegalIndexRoute
  '/_view/product/': typeof ViewProductIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/cal'
    | '/discord'
    | '/founders'
    | '/github'
    | '/join-waitlist'
    | '/linkedin'
    | '/x'
    | '/app'
    | '/docs'
    | '/pricing'
    | '/webhook/nango'
    | '/webhook/stripe'
    | '/'
    | '/app/account'
    | '/app/integration'
    | '/blog/$slug'
    | '/callback/auth'
    | '/changelog/$slug'
    | '/docs/$slug'
    | '/download/apple-silicon'
    | '/legal/$slug'
    | '/app/'
    | '/blog'
    | '/changelog'
    | '/docs/'
    | '/download'
    | '/legal'
    | '/product'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/cal'
    | '/discord'
    | '/founders'
    | '/github'
    | '/join-waitlist'
    | '/linkedin'
    | '/x'
    | '/pricing'
    | '/webhook/nango'
    | '/webhook/stripe'
    | '/'
    | '/app/account'
    | '/app/integration'
    | '/blog/$slug'
    | '/callback/auth'
    | '/changelog/$slug'
    | '/docs/$slug'
    | '/download/apple-silicon'
    | '/legal/$slug'
    | '/app'
    | '/blog'
    | '/changelog'
    | '/docs'
    | '/download'
    | '/legal'
    | '/product'
  id:
    | '__root__'
    | '/_view'
    | '/auth'
    | '/cal'
    | '/discord'
    | '/founders'
    | '/github'
    | '/join-waitlist'
    | '/linkedin'
    | '/x'
    | '/_view/app'
    | '/_view/docs'
    | '/_view/pricing'
    | '/webhook/nango'
    | '/webhook/stripe'
    | '/_view/'
    | '/_view/app/account'
    | '/_view/app/integration'
    | '/_view/blog/$slug'
    | '/_view/callback/auth'
    | '/_view/changelog/$slug'
    | '/_view/docs/$slug'
    | '/_view/download/apple-silicon'
    | '/_view/legal/$slug'
    | '/_view/app/'
    | '/_view/blog/'
    | '/_view/changelog/'
    | '/_view/docs/'
    | '/_view/download/'
    | '/_view/legal/'
    | '/_view/product/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ViewRouteRoute: typeof ViewRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CalRoute: typeof CalRoute
  DiscordRoute: typeof DiscordRoute
  FoundersRoute: typeof FoundersRoute
  GithubRoute: typeof GithubRoute
  JoinWaitlistRoute: typeof JoinWaitlistRoute
  LinkedinRoute: typeof LinkedinRoute
  XRoute: typeof XRoute
  WebhookNangoRoute: typeof WebhookNangoRoute
  WebhookStripeRoute: typeof WebhookStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/x': {
      id: '/x'
      path: '/x'
      fullPath: '/x'
      preLoaderRoute: typeof XRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin': {
      id: '/linkedin'
      path: '/linkedin'
      fullPath: '/linkedin'
      preLoaderRoute: typeof LinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-waitlist': {
      id: '/join-waitlist'
      path: '/join-waitlist'
      fullPath: '/join-waitlist'
      preLoaderRoute: typeof JoinWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders': {
      id: '/founders'
      path: '/founders'
      fullPath: '/founders'
      preLoaderRoute: typeof FoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discord': {
      id: '/discord'
      path: '/discord'
      fullPath: '/discord'
      preLoaderRoute: typeof DiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cal': {
      id: '/cal'
      path: '/cal'
      fullPath: '/cal'
      preLoaderRoute: typeof CalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_view': {
      id: '/_view'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ViewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_view/': {
      id: '/_view/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ViewIndexRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/webhook/stripe': {
      id: '/webhook/stripe'
      path: '/webhook/stripe'
      fullPath: '/webhook/stripe'
      preLoaderRoute: typeof WebhookStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhook/nango': {
      id: '/webhook/nango'
      path: '/webhook/nango'
      fullPath: '/webhook/nango'
      preLoaderRoute: typeof WebhookNangoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_view/pricing': {
      id: '/_view/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof ViewPricingRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/docs': {
      id: '/_view/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof ViewDocsRouteRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/app': {
      id: '/_view/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof ViewAppRouteRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/product/': {
      id: '/_view/product/'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ViewProductIndexRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/legal/': {
      id: '/_view/legal/'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof ViewLegalIndexRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/download/': {
      id: '/_view/download/'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof ViewDownloadIndexRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/docs/': {
      id: '/_view/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof ViewDocsIndexRouteImport
      parentRoute: typeof ViewDocsRouteRoute
    }
    '/_view/changelog/': {
      id: '/_view/changelog/'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ViewChangelogIndexRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/blog/': {
      id: '/_view/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof ViewBlogIndexRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/app/': {
      id: '/_view/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof ViewAppIndexRouteImport
      parentRoute: typeof ViewAppRouteRoute
    }
    '/_view/legal/$slug': {
      id: '/_view/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof ViewLegalSlugRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/download/apple-silicon': {
      id: '/_view/download/apple-silicon'
      path: '/download/apple-silicon'
      fullPath: '/download/apple-silicon'
      preLoaderRoute: typeof ViewDownloadAppleSiliconRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/docs/$slug': {
      id: '/_view/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof ViewDocsSlugRouteImport
      parentRoute: typeof ViewDocsRouteRoute
    }
    '/_view/changelog/$slug': {
      id: '/_view/changelog/$slug'
      path: '/changelog/$slug'
      fullPath: '/changelog/$slug'
      preLoaderRoute: typeof ViewChangelogSlugRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/callback/auth': {
      id: '/_view/callback/auth'
      path: '/callback/auth'
      fullPath: '/callback/auth'
      preLoaderRoute: typeof ViewCallbackAuthRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/blog/$slug': {
      id: '/_view/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof ViewBlogSlugRouteImport
      parentRoute: typeof ViewRouteRoute
    }
    '/_view/app/integration': {
      id: '/_view/app/integration'
      path: '/integration'
      fullPath: '/app/integration'
      preLoaderRoute: typeof ViewAppIntegrationRouteImport
      parentRoute: typeof ViewAppRouteRoute
    }
    '/_view/app/account': {
      id: '/_view/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof ViewAppAccountRouteImport
      parentRoute: typeof ViewAppRouteRoute
    }
  }
}

interface ViewAppRouteRouteChildren {
  ViewAppAccountRoute: typeof ViewAppAccountRoute
  ViewAppIntegrationRoute: typeof ViewAppIntegrationRoute
  ViewAppIndexRoute: typeof ViewAppIndexRoute
}

const ViewAppRouteRouteChildren: ViewAppRouteRouteChildren = {
  ViewAppAccountRoute: ViewAppAccountRoute,
  ViewAppIntegrationRoute: ViewAppIntegrationRoute,
  ViewAppIndexRoute: ViewAppIndexRoute,
}

const ViewAppRouteRouteWithChildren = ViewAppRouteRoute._addFileChildren(
  ViewAppRouteRouteChildren,
)

interface ViewDocsRouteRouteChildren {
  ViewDocsSlugRoute: typeof ViewDocsSlugRoute
  ViewDocsIndexRoute: typeof ViewDocsIndexRoute
}

const ViewDocsRouteRouteChildren: ViewDocsRouteRouteChildren = {
  ViewDocsSlugRoute: ViewDocsSlugRoute,
  ViewDocsIndexRoute: ViewDocsIndexRoute,
}

const ViewDocsRouteRouteWithChildren = ViewDocsRouteRoute._addFileChildren(
  ViewDocsRouteRouteChildren,
)

interface ViewRouteRouteChildren {
  ViewAppRouteRoute: typeof ViewAppRouteRouteWithChildren
  ViewDocsRouteRoute: typeof ViewDocsRouteRouteWithChildren
  ViewPricingRoute: typeof ViewPricingRoute
  ViewIndexRoute: typeof ViewIndexRoute
  ViewBlogSlugRoute: typeof ViewBlogSlugRoute
  ViewCallbackAuthRoute: typeof ViewCallbackAuthRoute
  ViewChangelogSlugRoute: typeof ViewChangelogSlugRoute
  ViewDownloadAppleSiliconRoute: typeof ViewDownloadAppleSiliconRoute
  ViewLegalSlugRoute: typeof ViewLegalSlugRoute
  ViewBlogIndexRoute: typeof ViewBlogIndexRoute
  ViewChangelogIndexRoute: typeof ViewChangelogIndexRoute
  ViewDownloadIndexRoute: typeof ViewDownloadIndexRoute
  ViewLegalIndexRoute: typeof ViewLegalIndexRoute
  ViewProductIndexRoute: typeof ViewProductIndexRoute
}

const ViewRouteRouteChildren: ViewRouteRouteChildren = {
  ViewAppRouteRoute: ViewAppRouteRouteWithChildren,
  ViewDocsRouteRoute: ViewDocsRouteRouteWithChildren,
  ViewPricingRoute: ViewPricingRoute,
  ViewIndexRoute: ViewIndexRoute,
  ViewBlogSlugRoute: ViewBlogSlugRoute,
  ViewCallbackAuthRoute: ViewCallbackAuthRoute,
  ViewChangelogSlugRoute: ViewChangelogSlugRoute,
  ViewDownloadAppleSiliconRoute: ViewDownloadAppleSiliconRoute,
  ViewLegalSlugRoute: ViewLegalSlugRoute,
  ViewBlogIndexRoute: ViewBlogIndexRoute,
  ViewChangelogIndexRoute: ViewChangelogIndexRoute,
  ViewDownloadIndexRoute: ViewDownloadIndexRoute,
  ViewLegalIndexRoute: ViewLegalIndexRoute,
  ViewProductIndexRoute: ViewProductIndexRoute,
}

const ViewRouteRouteWithChildren = ViewRouteRoute._addFileChildren(
  ViewRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ViewRouteRoute: ViewRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CalRoute: CalRoute,
  DiscordRoute: DiscordRoute,
  FoundersRoute: FoundersRoute,
  GithubRoute: GithubRoute,
  JoinWaitlistRoute: JoinWaitlistRoute,
  LinkedinRoute: LinkedinRoute,
  XRoute: XRoute,
  WebhookNangoRoute: WebhookNangoRoute,
  WebhookStripeRoute: WebhookStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
